Feature/czdev 272 activate signature request
coverzen/yousign-client pull request #11
Opened 2024-11-13 14:32 UTC by Martab93

### What kind of change does this PR introduce?
Feature.

### What is the new behavior?
Feat [CZDEV-272](https://coverzen.atlassian.net/browse/CZDEV-272)

### Does this PR introduce a breaking change?
No

### Other information:
N/A

2024-11-14 11:11 UTC, Pingus74 requested changes
Scusa @Martab93 mi fermo nella review, perhce mi sembra questa MR identica alla precefente, o almeno sto notando lo stesso coide in vari punti e mi sono accorto che sto segnalando le solite cose. 

Sono io rimbambito?

2024-11-14 11:11 UTC, Pingus74 commented on src/Structs/Soa/v1/ActivateSignatureResponse.php
> + * @property bool $optional
anche questo deve essere nullable, ma sinceramente lo lascerei cosi mettendo in attribute il default a false

2024-11-14 11:11 UTC, Pingus74 commented on src/Structs/Soa/v1/ActivateSignatureResponse.php
> +    protected $attributes = [
se ci metti il default del bool ok altrimenti toglilo

2024-11-14 11:11 UTC, Pingus74 commented on src/Structs/Soa/v1/AddSignerRequest.php
> + * @property array<int,SignerField> $fields
null

2024-11-14 11:11 UTC, Pingus74 commented on src/Structs/Soa/v1/AddSignerResponse.php
> + * @property array $info
metti tutte le prop null

2024-11-14 11:11 UTC, Pingus74 commented on src/Structs/Soa/v1/AddSignerResponse.php
> +                                                                    ->all();
indentazione

2024-11-15 08:39 UTC, Pingus74 commented on tests/Unit/Structs/Soa/v1/ActivateSignatureResponseTest.php
> +     * @covers \Coverzen\Components\YousignClient\Structs\Soa\v1\AddSignerRequest::factory
cove sbagliata

2024-11-15 08:39 UTC, Pingus74 commented on tests/Unit/Structs/Soa/v1/ActivateSignatureResponseTest.php
> +     * @covers \Coverzen\Components\YousignClient\Structs\Soa\v1\UploadDocumentRequest::factory
hai le cover sbagliate, ti sono rimaste della classe copiata

2024-12-03 14:27 UTC, Pingus74 submitted a review, later dismissed

2024-12-03 14:36 UTC, giraz82 submitted a review, later dismissed

2024-12-04 14:36 UTC, merged