Feature/get audit trail detail
coverzen/yousign-client pull request #14
Opened 2024-12-06 14:42 UTC by Martab93

### What kind of change does this PR introduce?
Feature.

### What is the new behavior?
Feat implement getAuditTrailDetail

### Does this PR introduce a breaking change?
No

### Other information:
N/A

2024-12-06 15:20 UTC, Pingus74 requested changes

2024-12-06 15:20 UTC, Pingus74 commented on src/Structs/Soa/v1/GetAuditTrailDetailResponse.php
> + * Class AddSignerRequest.
typo

2024-12-06 15:20 UTC, Pingus74 commented on src/Structs/Soa/v1/GetAuditTrailDetailResponse.php
> + * @property array|null $signature_request
Questa è una domanda...ti torna comodo il null? se hai dei foreach o map o simili potrebbe tornarti comodo un default a []

2024-12-06 16:48 UTC, giraz82 commented on src/Structs/Soa/v1/GetAuditTrailDetailResponse.php
> + * @property array|null $signature_request
Concordo, già segnalato altrove

2024-12-09 08:51 UTC, Pingus74 approved these changes

2024-12-09 08:54 UTC, merged